#%RAML 1.0
title: Challenge Tecnico API
description: Challenge para candidatos a Backend Developers - PatagonianTech
mediaType: application/json

/songs:
  description: Collection of available songs
  get:
    description: Get a list of songs based on the song title.
    queryParameters:
      artistName:
        description: "The name of the artist (case insensitive and doesn't need to match the whole name of the artist)"
        required: true
        minLength: 3
        type: string
        example: "Red Hot Chili"
    responses:
      200:
        body:
          application/json:
            example: |
              {
                "songs": [
                  {
                    "songId": "2TpxZ7JUBn3udsd6aR7qg68",
                    "songTitle": "Californication"
                  },
                  {
                    "songId": "1TuxZ7JU323uw46aR7qd6V",
                    "songTitle": "Otherside"
                  }
                ]
              }
  /{songId}:
    description: Song entity
    get:
      description: Get the song with `songId = {songId}`
      responses:
        200:
          body:
            application/json:
              example: |
                {
                  "artists": [
                    {
                      "external_urls": {
                        "spotify": "https://open.spotify.com/artist/08td7MxkoHQkXnWAYD8d6Q"
                      },
                      "href": "https://api.spotify.com/v1/artists/08td7MxkoHQkXnWAYD8d6Q",
                      "id": "08td7MxkoHQkXnWAYD8d6Q",
                      "name": "Tania Bowra",
                      "type": "artist",
                      "uri": "spotify:artist:08td7MxkoHQkXnWAYD8d6Q"
                    }
                  ],
                  "disc_number": 1,
                  "duration_ms": 276773,
                  "explicit": false,
                  "external_urls": {
                    "spotify": "https://open.spotify.com/track/2TpxZ7JUBn3uw46aR7qd6V"
                  },
                  "href": "https://api.spotify.com/v1/tracks/2TpxZ7JUBn3uw46aR7qd6V",
                  "id": "2TpxZ7JUBn3uw46aR7qd6V",
                  "is_local": false,
                  "is_playable": true,
                  "name": "All I Want",
                  "preview_url": "https://p.scdn.co/mp3-preview/12b8cee72118f995f5494e1b34251e4ac997445e?cid=774b29d4f13844c495f206cafdad9c86",
                  "track_number": 1,
                  "type": "track",
                  "uri": "spotify:track:2TpxZ7JUBn3uw46aR7qd6V"
                }
        404:
          body:
            application/json:
              example: |
                {"message": "Song not found"}